// const plans = [
//   "ZenCare Prime",
//   "ZenCare Plus",
//   "Flexi Care",
//   "Flexi Care Mini",
//   "ZenCare",
// ];

export const states = [
  "All",
  "Abia",
  "Abuja",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Bornu",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

// const types = ["Clinic", "Hospital", "Eye Care", "Dental Clinic", "Pharmacy"];

export const hospitals = [
  {
    name: "Hospital 1",
    type: "Hospital",
    plan: "ZenCare",
    state: "Ebonyi",
  },
  {
    name: "Hospital 2",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Gombe",
  },
  {
    name: "Hospital 3",
    type: "Hospital",
    plan: "ZenCare Plus",
    state: "Bayelsa",
  },
  {
    name: "Hospital 4",
    type: "Dental Clinic",
    plan: "ZenCare",
    state: "Kano",
  },
  {
    name: "Hospital 5",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Edo",
  },
  {
    name: "Hospital 6",
    type: "Clinic",
    plan: "Flexi Care",
    state: "Enugu",
  },
  {
    name: "Hospital 7",
    type: "Clinic",
    plan: "ZenCare Prime",
    state: "Bornu",
  },
  {
    name: "Hospital 8",
    type: "Dental Clinic",
    plan: "Flexi Care",
    state: "Ekiti",
  },
  {
    name: "Hospital 9",
    type: "Eye Care",
    plan: "Flexi Care Mini",
    state: "Bornu",
  },
  {
    name: "Hospital 10",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "Bauchi",
  },
  {
    name: "Hospital 11",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Sokoto",
  },
  {
    name: "Hospital 12",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Kano",
  },
  {
    name: "Hospital 13",
    type: "Eye Care",
    plan: "Flexi Care Mini",
    state: "Akwa Ibom",
  },
  {
    name: "Hospital 14",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Delta",
  },
  {
    name: "Hospital 15",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Ebonyi",
  },
  {
    name: "Hospital 16",
    type: "Hospital",
    plan: "Flexi Care",
    state: "All",
  },
  {
    name: "Hospital 17",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Lagos",
  },
  {
    name: "Hospital 18",
    type: "Dental Clinic",
    plan: "ZenCare",
    state: "Rivers",
  },
  {
    name: "Hospital 19",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "Adamawa",
  },
  {
    name: "Hospital 20",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "Sokoto",
  },
  {
    name: "Hospital 21",
    type: "Hospital",
    plan: "ZenCare",
    state: "Ebonyi",
  },
  {
    name: "Hospital 22",
    type: "Hospital",
    plan: "Flexi Care Mini",
    state: "Bayelsa",
  },
  {
    name: "Hospital 23",
    type: "Dental Clinic",
    plan: "ZenCare Plus",
    state: "Ogun",
  },
  {
    name: "Hospital 24",
    type: "Dental Clinic",
    plan: "Flexi Care",
    state: "Jigawa",
  },
  {
    name: "Hospital 25",
    type: "Hospital",
    plan: "ZenCare",
    state: "Bauchi",
  },
  {
    name: "Hospital 26",
    type: "Clinic",
    plan: "ZenCare",
    state: "Delta",
  },
  {
    name: "Hospital 27",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "All",
  },
  {
    name: "Hospital 28",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Kogi",
  },
  {
    name: "Hospital 29",
    type: "Pharmacy",
    plan: "ZenCare Prime",
    state: "Niger",
  },
  {
    name: "Hospital 30",
    type: "Pharmacy",
    plan: "ZenCare",
    state: "Adamawa",
  },
  {
    name: "Hospital 31",
    type: "Clinic",
    plan: "Flexi Care",
    state: "Benue",
  },
  {
    name: "Hospital 32",
    type: "Eye Care",
    plan: "Flexi Care Mini",
    state: "Niger",
  },
  {
    name: "Hospital 33",
    type: "Hospital",
    plan: "ZenCare Plus",
    state: "Ekiti",
  },
  {
    name: "Hospital 34",
    type: "Pharmacy",
    plan: "ZenCare Prime",
    state: "Kaduna",
  },
  {
    name: "Hospital 35",
    type: "Hospital",
    plan: "ZenCare Plus",
    state: "Ondo",
  },
  {
    name: "Hospital 36",
    type: "Dental Clinic",
    plan: "ZenCare Plus",
    state: "Rivers",
  },
  {
    name: "Hospital 37",
    type: "Clinic",
    plan: "Flexi Care",
    state: "All",
  },
  {
    name: "Hospital 38",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "Kogi",
  },
  {
    name: "Hospital 39",
    type: "Dental Clinic",
    plan: "Flexi Care",
    state: "Anambra",
  },
  {
    name: "Hospital 40",
    type: "Hospital",
    plan: "ZenCare",
    state: "Anambra",
  },
  {
    name: "Hospital 41",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Nasarawa",
  },
  {
    name: "Hospital 42",
    type: "Hospital",
    plan: "Flexi Care Mini",
    state: "Imo",
  },
  {
    name: "Hospital 43",
    type: "Clinic",
    plan: "Flexi Care Mini",
    state: "Bornu",
  },
  {
    name: "Hospital 44",
    type: "Pharmacy",
    plan: "ZenCare Prime",
    state: "Katsina",
  },
  {
    name: "Hospital 45",
    type: "Hospital",
    plan: "Flexi Care Mini",
    state: "Anambra",
  },
  {
    name: "Hospital 46",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Ekiti",
  },
  {
    name: "Hospital 47",
    type: "Hospital",
    plan: "ZenCare",
    state: "Yobe",
  },
  {
    name: "Hospital 48",
    type: "Eye Care",
    plan: "ZenCare Plus",
    state: "Adamawa",
  },
  {
    name: "Hospital 49",
    type: "Eye Care",
    plan: "Flexi Care Mini",
    state: "Anambra",
  },
  {
    name: "Hospital 50",
    type: "Clinic",
    plan: "ZenCare Prime",
    state: "Edo",
  },
  {
    name: "Hospital 51",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Oyo",
  },
  {
    name: "Hospital 52",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Imo",
  },
  {
    name: "Hospital 53",
    type: "Dental Clinic",
    plan: "ZenCare Prime",
    state: "Niger",
  },
  {
    name: "Hospital 54",
    type: "Hospital",
    plan: "ZenCare",
    state: "Bauchi",
  },
  {
    name: "Hospital 55",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Adamawa",
  },
  {
    name: "Hospital 56",
    type: "Hospital",
    plan: "ZenCare Plus",
    state: "Sokoto",
  },
  {
    name: "Hospital 57",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Delta",
  },
  {
    name: "Hospital 58",
    type: "Pharmacy",
    plan: "Flexi Care Mini",
    state: "Ogun",
  },
  {
    name: "Hospital 59",
    type: "Dental Clinic",
    plan: "ZenCare Plus",
    state: "Benue",
  },
  {
    name: "Hospital 60",
    type: "Hospital",
    plan: "ZenCare Plus",
    state: "Osun",
  },
  {
    name: "Hospital 61",
    type: "Pharmacy",
    plan: "Flexi Care",
    state: "Kogi",
  },
  {
    name: "Hospital 62",
    type: "Clinic",
    plan: "Flexi Care Mini",
    state: "Jigawa",
  },
  {
    name: "Hospital 63",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "Cross River",
  },
  {
    name: "Hospital 64",
    type: "Clinic",
    plan: "ZenCare Prime",
    state: "Bayelsa",
  },
  {
    name: "Hospital 65",
    type: "Pharmacy",
    plan: "ZenCare",
    state: "Edo",
  },
  {
    name: "Hospital 66",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Benue",
  },
  {
    name: "Hospital 67",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Kaduna",
  },
  {
    name: "Hospital 68",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Delta",
  },
  {
    name: "Hospital 69",
    type: "Clinic",
    plan: "Flexi Care Mini",
    state: "Ekiti",
  },
  {
    name: "Hospital 70",
    type: "Pharmacy",
    plan: "Flexi Care",
    state: "Abia",
  },
  {
    name: "Hospital 71",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Delta",
  },
  {
    name: "Hospital 72",
    type: "Clinic",
    plan: "Flexi Care",
    state: "Akwa Ibom",
  },
  {
    name: "Hospital 73",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Abuja",
  },
  {
    name: "Hospital 74",
    type: "Pharmacy",
    plan: "ZenCare Prime",
    state: "Ondo",
  },
  {
    name: "Hospital 75",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Yobe",
  },
  {
    name: "Hospital 76",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "Niger",
  },
  {
    name: "Hospital 77",
    type: "Pharmacy",
    plan: "ZenCare Prime",
    state: "Delta",
  },
  {
    name: "Hospital 78",
    type: "Clinic",
    plan: "ZenCare",
    state: "Kano",
  },
  {
    name: "Hospital 79",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Zamfara",
  },
  {
    name: "Hospital 80",
    type: "Eye Care",
    plan: "Flexi Care Mini",
    state: "Lagos",
  },
  {
    name: "Hospital 81",
    type: "Clinic",
    plan: "Flexi Care Mini",
    state: "Zamfara",
  },
  {
    name: "Hospital 82",
    type: "Eye Care",
    plan: "ZenCare",
    state: "Bornu",
  },
  {
    name: "Hospital 83",
    type: "Hospital",
    plan: "Flexi Care Mini",
    state: "Niger",
  },
  {
    name: "Hospital 84",
    type: "Dental Clinic",
    plan: "ZenCare Plus",
    state: "Bayelsa",
  },
  {
    name: "Hospital 85",
    type: "Hospital",
    plan: "Flexi Care",
    state: "Bornu",
  },
  {
    name: "Hospital 86",
    type: "Clinic",
    plan: "ZenCare",
    state: "Yobe",
  },
  {
    name: "Hospital 87",
    type: "Dental Clinic",
    plan: "Flexi Care",
    state: "Taraba",
  },
  {
    name: "Hospital 88",
    type: "Dental Clinic",
    plan: "ZenCare Plus",
    state: "Jigawa",
  },
  {
    name: "Hospital 89",
    type: "Pharmacy",
    plan: "ZenCare Plus",
    state: "Anambra",
  },
  {
    name: "Hospital 90",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "Osun",
  },
  {
    name: "Hospital 91",
    type: "Pharmacy",
    plan: "Flexi Care",
    state: "Taraba",
  },
  {
    name: "Hospital 92",
    type: "Dental Clinic",
    plan: "ZenCare Prime",
    state: "Bornu",
  },
  {
    name: "Hospital 93",
    type: "Clinic",
    plan: "ZenCare",
    state: "Enugu",
  },
  {
    name: "Hospital 94",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "Rivers",
  },
  {
    name: "Hospital 95",
    type: "Eye Care",
    plan: "Flexi Care Mini",
    state: "Benue",
  },
  {
    name: "Hospital 96",
    type: "Eye Care",
    plan: "ZenCare Prime",
    state: "Enugu",
  },
  {
    name: "Hospital 97",
    type: "Dental Clinic",
    plan: "ZenCare Prime",
    state: "Oyo",
  },
  {
    name: "Hospital 98",
    type: "Hospital",
    plan: "ZenCare Plus",
    state: "Benue",
  },
  {
    name: "Hospital 99",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "Adamawa",
  },
  {
    name: "Hospital 100",
    type: "Eye Care",
    plan: "ZenCare",
    state: "Zamfara",
  },
];

// for (let i = 0; i < 150; i++) {
//   const name = `Hospital ${i + 1}`;
//   const type = types[Math.floor(Math.random() * types.length)];
//   const plan = plans[Math.floor(Math.random() * plans.length)];
//   const state = states[Math.floor(Math.random() * states.length)];

//   hospitals.push({ name, type, plan, state });
// }

// export { hospitals };
// console.log({ hospitals });
