export const hospitals = [
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "lagos",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "abuja",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "enugu",
  },
  {
    name: "Flexi Care Mini Dental",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "kano",
  },
  { name: "ZenCare Pharmacy", type: "Pharmacy", plan: "ZenCare", state: "oyo" },
  // Repeat similar entries to make up to 100 or more times
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "abia",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "adamawa",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "akwa ibom",
  },
  {
    name: "Flexi Care Mini Dental",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "anambra",
  },
  {
    name: "ZenCare Pharmacy",
    type: "Pharmacy",
    plan: "ZenCare",
    state: "bauchi",
  },
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "bayelsa",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "benue",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "bornu",
  },
  {
    name: "Flexi Care Mini Dental",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "cross river",
  },
  {
    name: "ZenCare Pharmacy",
    type: "Pharmacy",
    plan: "ZenCare",
    state: "delta",
  },
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "ebonyi",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "edo",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "ekiti",
  },
  { name: "ZenCare Pharmacy", type: "Pharmacy", plan: "ZenCare", state: "oyo" },
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "abia",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "adamawa",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "akwa ibom",
  },
  {
    name: "Flexi Care Mini Dental",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "anambra",
  },
  {
    name: "ZenCare Pharmacy",
    type: "Pharmacy",
    plan: "ZenCare",
    state: "bauchi",
  },
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "bayelsa",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "benue",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "bornu",
  },
  {
    name: "Flexi Care Mini Dental",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "cross river",
  },
  {
    name: "ZenCare Pharmacy",
    type: "Pharmacy",
    plan: "ZenCare",
    state: "delta",
  },
  {
    name: "ZenCare Prime Hospital",
    type: "Hospital",
    plan: "ZenCare Prime",
    state: "ebonyi",
  },
  {
    name: "ZenCare Plus Clinic",
    type: "Clinic",
    plan: "ZenCare Plus",
    state: "edo",
  },
  {
    name: "Flexi Care Eye Center",
    type: "Eye Care",
    plan: "Flexi Care",
    state: "ekiti",
  },
  {
    name: "Flexi Care Mini Dental",
    type: "Dental Clinic",
    plan: "Flexi Care Mini",
    state: "gombe",
  },
  { name: "ZenCare Pharmacy", type: "Pharmacy", plan: "ZenCare", state: "imo" },

  // Add more dummy data as needed
];

export const states = [
  "all",
  "abia",
  "abuja",
  "adamawa",
  "akwa ibom",
  "anambra",
  "bauchi",
  "bayelsa",
  "benue",
  "bornu",
  "cross river",
  "delta",
  "ebonyi",
  "edo",
  "ekiti",
  "enugu",
  "gombe",
  "imo",
  "jigawa",
  "kaduna",
  "kano",
  "katsina",
  "kebbi",
  "kogi",
  "kwara",
  "lagos",
  "nasarawa",
  "niger",
  "ogun",
  "ondo",
  "osun",
  "oyo",
  "plateau",
  "rivers",
  "sokoto",
  "taraba",
  "yobe",
  "zamfara",
];
